services:
  keycloak.postgres:
    image: postgres:17
    container_name: keycloak.postgres
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d keycloakdb -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"
    networks:
      - keycloak_network
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: ["start-dev"]
    environment:
      KC_HEALTH_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak.postgres:5432/keycloakdb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: "${POSTGRES_PASSWORD}"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY: edge
    ports:
      - "8080:8080"
    depends_on:
      keycloak.postgres:
        condition: service_healthy
      mailpit:
        condition: service_started
    networks:
      - keycloak_network

  mailpit:
    image: axllent/mailpit@sha256:c076638db1e15662150be4fb62b8a6e96ef6ba5bde90c838a0239225854830f7
    container_name: mailpit
    environment:
      - MP_DATABASE=/data/mailpit.db
      - MP_UI_AUTH=${MP_UI_AUTH}
      - TZ=America/Phoenix
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit_data:/data
    networks:
      - keycloak_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
    networks:
      - keycloak_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  keycloak_network:
    driver: bridge

volumes:
  keycloak_postgres_data:
  mailpit_data:
  pgadmin_data:
